# DEFINE
maxthreads: 10
# DIRS
genomes_type: 'refseq'
genomes_source: 'genomes'
phrog_db: '~/Tools/databases/phrogs_v_4'

# PARAMETERS
prefilter_ann: 0  # after PHANOTATE
# OUTPUT DIRS
# snake_annotate_genomes:
annotation_dir: 'annotation'
annotation_dir_nucl: 'annotation/cds'
annotation_dir_prot: 'annotation/prot'
prot_db_dir: 'whole_proteome_db'
domains_dir: 'domains'
domains_tables_dir: 'domains/tables'
# DEFAULT
scripts: 'scripts'
meta: 'meta'
envs: 'envs'