# DEFINE
# PARAMETERS
# annotation
prefilter_ann: -1  # after PHANOTATE
maxthreads: 10
genomes_type: 'c-c-combo!'
filter_strand: True
maxram: 25G
maxmem: 80G
# filtering genomes
manual_choice_genomes: False
# if manual choise is True, specify path to file with genome IDs
manual_choice_path: ''
min_tdr_len: 99
min_tdr_de: 0.3
masking_threshold: -3
max_genome_len: 65000
max_dist_to_pol_tdr: 5000
max_dist_to_pol_inter: 5000
min_dist_to_pol_inter: 1000
min_intergenic_len: 500
max_intergenic_len: 3000  # means long other-strand region -> wrong organization
max_dist_from_pol: 5000
clu_min_seq_id: 0.3
clu_min_cov: 0.7
min_seq_msa: 3
hhsearch_eval_thres: 0.00005
haircut_score_cl1: 0.4
hmmer_eval_thres: 0.0005
# DIRS
phrog_db: '~/dbs/phrogs_v_4'
phrog_desc: '../../dbs/phrogs_v_4/phrog_annot_v4.tsv'
pfam_path: '~/dbs/pfam_21_11_15/Pfam-A.hmm'
dbapis_path:  '~/dbs/dbapis/dbAPIS.hmm'
dbapis_desc:  '~/dbs/dbapis/dbAPIS_info.tsv'
# OUTPUT DIRS
data: 'data_autographiviridae'
# snake_annotate_genomes:
annotation_dir: 'data_autographiviridae/annotation'
annotation_dir_nucl: 'data_autographiviridae/annotation/cds'
annotation_dir_prot: 'data_autographiviridae/annotation/prot'
annotation_dir_table: 'data_autographiviridae/annotation/coords'
genomes_source: 'data_autographiviridae/genomes'

mmseqs_db: 'data_autographiviridae/mmseqs_dbs'
mmseqs_temp: 'mmseqs_temp'


target_prot_db_dir:  'data_autographiviridae/mmseqs_dbs/target_proteome_db'
target_clu_db_dir:  'data_autographiviridae/mmseqs_dbs/target_clu_proteome_db'
target_clu_reprs_db_dir: 'data_autographiviridae/mmseqs_dbs/target_clu_reprs_db'
target_clu_msa_db_dir: 'data_autographiviridae/mmseqs_dbs/target_msa_db'
target_msa_unpacked_db_dir: 'data_autographiviridae/mmseqs_dbs/target_msa_db/msa_unpacked'
target_hhsuite_db_dir: 'data_autographiviridae/mmseqs_dbs/target_msa_db/hhdb'

target_clu_msa_dir: 'data_autographiviridae/mmseqs_dbs/target_msa'
target_msa_unpacked_dir: 'data_autographiviridae/mmseqs_dbs/target_msa/msa_unpacked'

target_clans_info_dir: 'data_autographiviridae/clans_pre_info'
target_clans_concat_dir: 'data_autographiviridae/clans_info'

domains_dir: 'data_autographiviridae/domains'
domains_tables_dir: 'data_autographiviridae/domains/tables'
target_prot_dom_db_dir:  'data_autographiviridae/mmseqs_dbs/target_proteome_domains_db'


intergenic_dir: 'data_autographiviridae/intergenics'

target_dir: 'data_autographiviridae/target_loci'

# analyse known adgs
known_interest_dir: 'data_autographiviridae/known_adgs_analysis'
alignments_dir: 'data_autographiviridae/known_adgs_analysis/alignments'
alignments_trimmed_dir: 'data_autographiviridae/known_adgs_analysis/alignments_trimmed'
trees_dir: 'data_autographiviridae/known_adgs_analysis/trees'

# find novel adgs
similarity_dir: 'data_autographiviridae/loci_similarity'
permutations_dir: 'data_autographiviridae/loci_similarity/permutations'
num_permutations: 1000

clans: '###'
# DEFAULT
scripts: 'scripts'
meta: 'metadata'
envs: 'envs'
pics: 'data_autographiviridae/pics'
cl1_path: '~/tools/clusterone/cluster_one-1.0.jar'
