# DEFINE
# PARAMETERS
# annotation
checkv_completeness_thres: 90.0
min_contig_len: 2400
prefilter_ann: -1  # after PHANOTATE
maxthreads: 32
genomes_type: 'meta'
filter_strand: True
maxram: 300G
maxmem: 80G
# filtering genomes
manual_choice_genomes: False
# if manual choise is True, specify path to file with genome IDs
manual_choice_path: ''
min_tdr_len: 99
min_tdr_de: 0.3
masking_threshold: -3
max_genome_len: 65000
max_dist_to_pol_tdr: 5000
max_dist_to_pol_inter: 5000
min_dist_to_pol_inter: 1000
min_intergenic_len: 500
max_intergenic_len: 3000  # means long other-strand region -> wrong organization
max_dist_from_pol: 5000
clu_min_seq_id: 0.3
clu_min_cov: 0.7
min_seq_msa: 3
hhsearch_eval_thres: 0.00005
haircut_score_cl1: 0.4
hmmer_eval_thres: 0.0005
# DIRS
samples_description: 'mags_samples_actions.tsv'
db_fastas: '/home/niagara/Storage/IBG/O_Kotovskaya/dbs/meta_vir'
#db_fastas: '/home/oxalotl/Tools/databases/meta_vir'

phrog_db: '~/dbs/phrogs_v_4'
phrog_desc: '../../dbs/phrogs_v_4/phrog_annot_v4.tsv'
pfam_path: '~/dbs/pfam_21_11_15/Pfam-A.hmm'
dbapis_path:  '~/dbs/dbapis/dbAPIS.hmm'
dbapis_desc:  '~/dbs/dbapis/dbAPIS_info.tsv'
# OUTPUT DIRS
data: 'data_autographiviridae_meta'
# snake_annotate_genomes:
#checkv_db_path: '/home/niagara/Storage/IBG/O_Kotovskaya/dbs/checkv_db'
checkv_db_path: 'metadata/checkv_db'
checkv_output: 'data_autographiviridae_meta/completenesses'
contigs_dir: 'data_autographiviridae_meta/filtered_contigs'
all_contigs_dir: 'data_autographiviridae_meta/mags'
annotation_dir: 'data_autographiviridae_meta/annotation'
annotation_dir_nucl: 'data_autographiviridae_meta/annotation/cds'
annotation_dir_prot: 'data_autographiviridae_meta/annotation/prot'
annotation_dir_table: 'data_autographiviridae_meta/annotation/coords'

filtered_contigs_dir: 'data_autographiviridae_meta/filtered_mags'
genomes_source: 'data_autographiviridae_meta/filtered_mags_flatten'

mmseqs_db: 'data_autographiviridae_meta/mmseqs_dbs'
mmseqs_temp: 'mmseqs_temp'


early_prot_db_dir:  'data_autographiviridae_meta/mmseqs_dbs/early_proteome_db'
early_clu_db_dir:  'data_autographiviridae_meta/mmseqs_dbs/early_clu_proteome_db'
early_clu_reprs_db_dir: 'data_autographiviridae_meta/mmseqs_dbs/early_clu_reprs_db'
early_clu_msa_db_dir: 'data_autographiviridae_meta/mmseqs_dbs/early_msa_db'
early_msa_unpacked_db_dir: 'data_autographiviridae_meta/mmseqs_dbs/early_msa_db/msa_unpacked'
early_hhsuite_db_dir: 'data_autographiviridae_meta/mmseqs_dbs/early_msa_db/hhdb'

early_clu_msa_dir: 'data_autographiviridae_meta/mmseqs_dbs/early_msa'
early_msa_unpacked_dir: 'data_autographiviridae_meta/mmseqs_dbs/early_msa/msa_unpacked'

early_clans_info_dir: 'data_autographiviridae_meta/clans_pre_info'
early_clans_concat_dir: 'data_autographiviridae_meta/clans_info'

domains_dir: 'data_autographiviridae_meta/domains'
domains_tables_dir: 'data_autographiviridae_meta/domains/tables'
early_prot_dom_db_dir:  'data_autographiviridae_meta/mmseqs_dbs/early_proteome_domains_db'

repeats_dir: 'data_autographiviridae_meta/tdrs'
repeats_per_genome_dir: 'data_autographiviridae_meta/tdrs/per_genome'

intergenic_dir: 'data_autographiviridae_meta/intergenics'

upstreams_dir: 'data_autographiviridae_meta/upstreams'

# DEFAULT
scripts: 'scripts'
meta: 'metadata'
envs: 'envs'
pics: 'data_autographiviridae_meta/pics'
cl1_path: '~/tools/clusterone/cluster_one-1.0.jar'
